// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/companion/HomeScreen.tsx": () => import("../components/mockups/companion/HomeScreen.tsx"),
  "./components/mockups/companion/HomeScreenLight.tsx": () => import("../components/mockups/companion/HomeScreenLight.tsx")
};
